# Generated by Django 4.0.3 on 2022-12-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='automobile',
            new_name='auto',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='sales_person',
            new_name='employee',
        ),
    ]
