# Generated by Django 4.0.3 on 2022-12-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
