# Generated by Django 4.0.3 on 2022-12-07 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
