# Generated by Django 4.0.3 on 2022-12-11 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='vip',
            new_name='completed',
        ),
    ]
