# Generated by Django 4.0.3 on 2022-12-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='time',
        ),
        migrations.AddField(
            model_name='service',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
