# Generated by Django 4.0.3 on 2022-12-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_remove_service_date_remove_service_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='service',
            name='vin',
            field=models.CharField(max_length=17),
        ),
    ]
