# Generated by Django 4.0.3 on 2022-12-08 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_automobilevo_vin_alter_service_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='date_time',
        ),
        migrations.AddField(
            model_name='service',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
